(function(){function t(a,b,c,d){b=b||a;var e=c||a;c=e[0]-b[0];b=e[1]-b[1];d=Math.atan2(b,c)+(d?Math.PI:0);c=.15*Math.sqrt(Math.pow(c,2)+Math.pow(b,2));return[a[0]+Math.cos(d)*c,a[1]+Math.sin(d)*c]}function w(a){return a.reduce(function(a,c,d,e){if(1==d)a="M "+c[0]+","+c[1];else{var b=t(e[d-1],e[d-2],c);d=t(c,e[d-1],e[d+1],!0);a+="C "+b[0]+","+b[1]+" "+d[0]+","+d[1]+" "+c[0]+","+c[1]}return a})}function q(a,b,c){if(!b)return"";var d=a.labelSizeX,e=a.labelSizeY,g=a.size,n,l,p='\x3cg clip-path\x3d"url(#clip-path-'+
    a.id+')"\x3e',r=[];f(b).each(function(b,k){var m=a.width*d+k*g;"bar"==a.type&&(m=a.width*d+k*g+g/2);var h=a.height*(1-2*e);b=h-b/a.max*h+a.height*e;"bezier"==a.type&&(0==k&&r.push([m,b]),r.push([m,b]));m=m.toFixed(2);b=b.toFixed(2);if("line"==a.type||"bezier"==a.type)"line"==a.type&&0<k&&(p+='\x3cpath stroke-linecap\x3d"round" stroke-width\x3d"'+Math.min(4,g/4)+'" stroke-opacity\x3d"0.75" stroke\x3d"'+c[k%c.length]+'" fill\x3d"none" d\x3d"M'+n+","+l+"L"+m+","+b+'"/\x3e'),p+='\x3ccircle fill\x3d"'+
    c[k%c.length]+'" cx\x3d"'+m+'" cy\x3d"'+b+'" r\x3d"'+Math.min(3,g/6)+'"/\x3e';"bar"==a.type&&(p+='\x3cpath stroke-width\x3d"'+.8*g+'" stroke-opacity\x3d"0.75" stroke\x3d"'+c[k%c.length]+'" d\x3d"M'+m+","+b+"L"+m+","+a.height*(1-e)+'"/\x3e');n=m;l=b});"bezier"==a.type&&(p+='\x3cpath stroke-width\x3d"'+Math.min(4,g/4)+'" stroke-opacity\x3d"0.75" stroke\x3d"'+c[0]+'" fill\x3d"none" d\x3d"'+w(r)+'"/\x3e');return p+="\x3c/g\x3e"}function u(a){if(!a.width)return"";a.chartLabelsColor||(a.chartLabelsColor=
    "var(--color-gray1)");a.chartAxisColor||(a.chartAxisColor="var(--color-gray1)");a.chartGridColor||(a.chartGridColor="var(--color-gray4)");a.isPercentage||(a.isPercentage=!1);var b=Math.random().toString(36).substr(2,9),c="",d=.15,e=.15;a.labels?(d=Math.min(.15,96/a.width),e=Math.min(.15,96/a.height)):(d=3/a.width,e=3/a.height);var g=a.width*(1-2*d)/(a.values.length-1);"bar"==a.type&&(g=a.width*(1-2*d)/a.values.length);a.labelSizeX=d;a.labelSizeY=e;a.size=g;a.id=b;a.x0=Math.round(a.width*d);a.y0=Math.round(a.height*
    e);a.x1=Math.round(a.width*(1-d));a.y1=Math.round(a.height*(1-e));c+='\x3cdiv style\x3d"position:relative;width:100%;height:'+a.height+'px;"\x3e';for(b=0;b<a.yaxis;b++){var n=a.x0,l=a.y0-6+a.height*(1-2*e)*b/a.yaxis;a.labels&&(c+='\x3cdiv class\x3d"chart-labels" style\x3d"width:'+a.x0+"px;text-align:right;position:absolute;font-size:12px;line-height:12px;left:0px;top:"+l+"px;color:"+a.chartLabelsColor+'"\x3e'+Math.round(a.max*(1-b/a.yaxis))+(a.isPercentage?" %":"")+"\x26nbsp;\x26nbsp;\x3c/div\x3e")}f(a.labels).each(function(b,
    l){var h=Math.min(Math.max(9,g/2),15),k=a.width*d+l*g-h/2+2;"bar"==a.type&&(k=a.width*d+l*g+g/2-h/2+2);c=window.navigator?c+('\x3cdiv class\x3d"chart-labels" style\x3d"writing-mode:tb-rl;width:'+h+"px;height:"+a.y0+"px;position:absolute;font-size:"+h+"px;line-height:"+h+"px;left:"+k+"px;top:"+a.height*(1-e)+"px;color:"+a.chartLabelsColor+'"\x3e\x26nbsp;\x26nbsp;'+b+"\x3c/div\x3e"):c+('\x3ctable style\x3d"position:absolute;left:'+k+"px;top:"+a.height*(1-e)+'px;"\x3e\x3ctr\x3e\x3ctd class\x3d"chart-labels" style\x3d"writing-mode:tb-rl;width:'+
    h+"px;height:"+2*a.y0+"px;font-size:"+h+"px;line-height:"+h+"px;color:"+a.chartLabelsColor+'"\x3e\x26nbsp;\x26nbsp;'+b+"\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e")});c+='\x3csvg viewBox\x3d"0,0,'+a.width+","+a.height+'" width\x3d"'+a.width+'" height\x3d"'+a.height+'"\x3e';for(b=0;b<a.yaxis;b++)n=a.x0,l=Math.round(a.height*e+a.height*(1-2*e)*b/a.yaxis),c+='\x3cpath class\x3d"chart-grid" fill\x3d"none" stroke\x3d"'+a.chartGridColor+'" stroke-width\x3d"1" d\x3d"M'+n+","+l+"L"+a.x1+","+l+'"/\x3e';if("line"==
    a.type||"bezier"==a.type)c+='\x3cpath class\x3d"chart-axis" fill\x3d"none" stroke-width\x3d"3" stroke-linecap\x3d"round" stroke\x3d"'+a.chartAxisColor+'" d\x3d"M'+a.x0+","+a.y0+"L"+a.x0+","+a.y1+"L"+a.x1+","+a.y1+'"/\x3e';c+=q(a,a.values,a.colors);c+=q(a,a.values1,a.colors1);c+=q(a,a.values2,a.colors2);c+=q(a,a.values3,a.colors3);"bar"==a.type&&(c+='\x3cpath class\x3d"chart-axis" fill\x3d"none" stroke-width\x3d"3" stroke-linecap\x3d"round" stroke\x3d"'+a.chartAxisColor+'" d\x3d"M'+a.x0+","+a.y0+"L"+
    a.x0+","+a.y1+"L"+a.x1+","+a.y1+'"/\x3e');c+="\x3c/svg\x3e";return c+="\x3c/div\x3e"}function v(){f(".f-chart").each(function(a,b){b=a.getBoundingClientRect();var c=JSON.parse(a.dataset.json);c.width=b.width;f(a).html(f().chart(c).render())})}f().prototype().chart=function(a){var b={};b.options=a;b.render=function(){return u(b.options)};return b};f(window).on("resize",v);f().uiPlugins().push(function(a,b){var c=f(b.div).find(".f_chart").item;c?(f(c).removeClass("f_chart").addClass("f-chart"),a=JSON.parse(f(c).html()),
c.dataset.json=JSON.stringify(a),f(c).html(u(a)),f(b.div).uiRender(b.callback)):a(b)});f().uiOnReadyPlugins().push(v)})();