(function(){function k(){f(".f-a4h").each(function(a,b){b=a.parentElement.getBoundingClientRect();a.style.height=Math.round(2100*b.width/2970)+"px"});f(".f-a4v").each(function(a,b){b=a.parentElement.getBoundingClientRect();a.style.height=Math.round(2970*b.width/2100)+"px"});f(".f-16_9").each(function(a,b){b=a.parentElement.getBoundingClientRect();a.style.height=Math.round(9*b.width/16)+"px"});f(".f-square").each(function(a,b){b=a.parentElement.getBoundingClientRect();a.style.height=Math.round(b.width)+
      "px"});f(".f-stage").each(function(a,b){var c=a.parentElement.getBoundingClientRect();b=parseInt(a.getAttribute("data-width"));var d=parseInt(a.getAttribute("data-height")),e=c.width;c=c.height;var g=e/b;e/c>b/d&&(g=c/d);a.style.position="absolute";a.style.top="50%";a.style.left="50%";a.style.width=b+"px";a.style.height=d+"px";a.style.transform="translate(-50%,-50%) scale("+g+","+g+")";a.setAttribute("scale",g)})}var h;f().prototype().serverURL=function(a){if(a)h=a;else{if(h)return h;if(document.location){var b=
  document.location.protocol+"//"+document.location.hostname;document.location.port&&""!=document.location.port&&(b=b+":"+document.location.port);b+="/";h=a}return b}};String.prototype.equals=function(a){try{return this.toString()===a.toString()}catch(b){return!1}};String.prototype.equalsIgnoreCase=function(a){try{return this.toLowerCase().equals(a.toLowerCase())}catch(b){return!1}};String.prototype.contains=function(a){try{return-1!=this.indexOf(a)}catch(b){return!1}};String.prototype.containsIgnoreCase=
  function(a){try{return this.toLowerCase().contains(a.toLowerCase())}catch(b){return!1}};String.prototype.startsWith=function(a){try{var b=this.indexOf(a),c=b+a.length,d=this.substring(b,c),e=this.substring(0,c);return d.equals(e)}catch(g){return!1}};String.prototype.capitalize=function(){return this.charAt(0).toUpperCase()+this.slice(1)};Date.parse=function(a){try{if("string"==typeof a){var b=a.split(/[^0-9]/);return new Date(b[0],1<b.length?b[1]-1:0,2<b.length?b[2]:0,3<b.length?b[3]:0,4<b.length?
  b[4]:0,5<b.length?b[5]:0)}return new Date(a)}catch(c){return new Date}};Date.prototype.isInvalid=function(){return isNaN(this.getTime())?!0:!1};Date.prototype.getTimestamp=function(){return this.getTime()/1E3};Date.prototype.getISOTimestamp=function(){return Date.parse(this.toISOString()).getTime()/1E3};Date.prototype.add=function(a,b){"minutes"==a?this.setTime(this.getTime()+6E4*b):"hours"==a?this.setTime(this.getTime()+36E5*b):"days"==a&&this.setTime(this.getTime()+864E5*b);return this};Date.prototype.clone=
  function(){return new Date(this)};Date.prototype.yesterday=function(){this.setDate(this.getDate()-1);return this};Date.prototype.tomorrow=function(){this.setDate(this.getDate()+1);return this};Date.prototype.prevYear=function(){this.setFullYear(this.getFullYear()-1);return this};Date.prototype.nextYear=function(){this.setFullYear(this.getFullYear()+1);return this};Date.prototype.prevMonth=function(){this.setMonth(this.getMonth()-1);return this};Date.prototype.nextMonth=function(){this.setMonth(this.getMonth()+
    1);return this};Date.prototype.prevWeek=function(){this.setDate(this.getDate()-7);return this};Date.prototype.nextWeek=function(){this.setDate(this.getDate()+7);return this};Date.prototype.dayStart=function(){this.setHours(0);this.setMinutes(0);this.setSeconds(0);return this};Date.prototype.dayEnd=function(){this.setHours(23);this.setMinutes(59);this.setSeconds(59);return this};Date.prototype.monthStart=function(){this.setDate(1);this.dayStart();return this};Date.prototype.monthEnd=function(){this.setDate(this.getMaxDayOfMonth());
    this.dayEnd();return this};Date.prototype.getMaxDayOfMonth=function(){for(var a=new Date(this.getFullYear(),this.getMonth(),1),b=0;a.getMonth()==this.getMonth();)b++,a.tomorrow();return b};Date.prototype.getStartOfWeek=function(){for(;1!=this.getDay();)this.setDate(this.getDate()-1);return this};Date.prototype.getWeeksInMonth=function(){return Math.ceil(this.getMaxDayOfMonth()/7)};Date.prototype.getWeeksInYear=function(){for(var a=new Date(this.getFullYear(),0,1),b=0;a.getFullYear()==this.getFullYear();)b+=
  a.getMaxDayOfMonth(),a.nextMonth();return Math.round(b/7)};Date.prototype.getMonthMonday=function(){this.setDate(1);this.getStartOfWeek();return this};Date.prototype.format=function(a,b){if(a)return this.toLocaleDateString(b||"en",a);a=("000"+(this.getMonth()+1)).slice(-2);b=("000"+this.getDate()).slice(-2);var c=("000"+this.getHours()).slice(-2),d=("000"+this.getMinutes()).slice(-2),e=("000"+this.getSeconds()).slice(-2);return this.getFullYear()+"-"+a+"-"+b+" "+c+":"+d+":"+e};Date.prototype.datetimeAsParam=
  function(){return this.format()};Date.prototype.dateAsParam=function(){var a=("000"+(this.getMonth()+1)).slice(-2),b=("000"+this.getDate()).slice(-2);return this.getFullYear()+"-"+a+"-"+b};Date.prototype.datetimeAsParam=function(){var a=("000"+(this.getMonth()+1)).slice(-2),b=("000"+this.getDate()).slice(-2),c=("000"+this.getHours()).slice(-2),d=("000"+this.getMinutes()).slice(-2);return this.getFullYear()+"-"+a+"-"+b+" "+c+":"+d};Date.prototype.time=function(a,b){a=a||{};return this.toLocaleTimeString(b||
    "en",a)};String.prototype.normalize=function(){for(var a="",b=0;b<this.length;b++){var c=this.charAt(b);a=isNaN(c)&&c==c.toUpperCase()?a+("-"+c.toLowerCase()):a+c}return a};String.prototype.replaceAll=function(a,b){return this.split(a).join(b)};JSON.parse=function(a){eval("var json \x3d "+a);return json};f(window).on("resize",function(){k()});f().uiOnReadyPlugins().push(k);f().uiOnReadyPlugins().push(function(){f(".f-overlay").each(function(a){a.dataset.background&&(a.style.backgroundImage="url("+
a.dataset.background+")")})})})();